EnterpriseAssignment2/Models/Intervention.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Intervention
    {
        public int InterventionId { get; set; }
        [Display(Name = "Client Name")]
        public int ClientId { get; set; }
        [Display(Name = "Proposing User")]
        public string ProposingUser { get; set; }
        [Display(Name = "Approving User")]
        public string ApprovalUser { get; set; }
        public int Type { get; set; }
        [Display(Name = "Labour Required")]
        public decimal LabourRequired { get; set; }
        public decimal Cost { get; set; }
        [Display(Name = "Performed Date")]
        public Nullable<System.DateTime> PerformedDate { get; set; }
        public string State { get; set; }
        [Display(Name = "RecentVisit Date")]
        public Nullable<System.DateTime> RecentVisitDate { get; set; }
        [Display(Name = "Remaining Life")]
        public int RemainingLife { get; set; }
        public string Note { get; set; }

        [Display(Name = "Proposing User")]
        public virtual AspNetUsers ProposingUserObject { get; set; }
        [Display(Name = "Approval User")]
        public virtual AspNetUsers ApprovalUserObject { get; set; }
        [Display(Name = "Client")]
        public virtual Client Client { get; set; }
        [Display(Name = "Intervention Type")]
        public virtual InterventionType InterventionType { get; set; }
    }
}

EnterpriseAssignment2/Models/InterventionType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseAssignment2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InterventionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterventionType()
        {
            this.Intervention = new HashSet<Intervention>();
        }
    
        public int Id { get; set; }
        [Display(Name = "Type Name")]
        public string TypeName { get; set; }
        public decimal DefaultLabour { get; set; }
        public decimal DefaultCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervention> Intervention { get; set; }
    }
}

EnterpriseAssignment2/Controllers/InterventionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EnterpriseAssignment2.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using EnterpriseAssignment2.Services;
using System.Threading.Tasks;

namespace EnterpriseAssignment2.Controllers
{
    [Authorize(Roles = "SiteEngineer")]
    public class InterventionController : Controller
    {

        IInterventionService service = new InterventionService();
        public InterventionController()
        {
            service = new InterventionService();
        }

        public InterventionController(IInterventionService mockService)
        {
            service = mockService;
        }

        // GET: Intervention
        public ActionResult List_Client(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var intervention = service.ListInterventionsByClientId(id);
            return View(intervention);
        }

        public ActionResult History()
        {
            var intervention = service.ListInterventionsByEngineer(User);
            return View(intervention);
        }


        // GET: Intervention/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intervention intervention = service.FindInterventionById(id);
            if (intervention == null)
            {
                return HttpNotFound();
            }
            return View(intervention);
        }

        // GET: Intervention/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.ApprovalUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email");
            ViewBag.ProposingUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email");
            ViewBag.ClientId = new SelectList(service.GetClientById(id), "ClientId", "Name");
            ViewBag.Type = new SelectList(service.GetInterventionTypeSet(), "Id", "TypeName");
            return View();
        }

        // POST: Intervention/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InterventionId,ClientId,ProposingUser,ApprovalUser,Type,LabourRequired,Cost,PerformedDate,State,RecentVisitDate,RemainingLife,Note")] Intervention intervention)
        {
            if (ModelState.IsValid)
            {
                var clientId = intervention.ClientId;
                service.CreateIntervention(intervention, User);
                return RedirectToAction("List_Client/" + clientId);
            }

            ViewBag.ApprovalUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email", intervention.ApprovalUser);
            ViewBag.ProposingUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email", intervention.ProposingUser);
            ViewBag.ClientId = new SelectList(service.GetClientSet(), "ClientId", "Name", intervention.ClientId);
            ViewBag.Type = new SelectList(service.GetInterventionTypeSet(), "Id", "TypeName", intervention.Type);
            return View(intervention);
        }

        // GET: Intervention/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intervention intervention = service.FindInterventionById(id);
            intervention.RecentVisitDate = DateTime.Now;
            if (intervention == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApprovalUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email", intervention.ApprovalUser);
            ViewBag.ProposingUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email", intervention.ProposingUser);
            ViewBag.ClientId = new SelectList(service.GetClientSet(), "ClientId", "Name", intervention.ClientId);
            ViewBag.Type = new SelectList(service.GetInterventionTypeSet(), "Id", "TypeName", intervention.Type);
            return View(intervention);
        }

        // POST: Intervention/Edit/5s
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InterventionId,ClientId,ProposingUser,ApprovalUser,Type,LabourRequired,Cost,PerformedDate,State,RecentVisitDate,RemainingLife,Note")] Intervention intervention)
        {
            if (ModelState.IsValid)
            {
                service.UpdateIntervention(intervention);
                return RedirectToAction("List_Client/" + service.FindInterventionById(intervention.InterventionId).ClientId);
            }
            ViewBag.ApprovalUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email", intervention.ApprovalUser);
            ViewBag.ProposingUser = new SelectList(service.GetAspNetUsersSet(), "Id", "Email", intervention.ProposingUser);
            ViewBag.ClientId = new SelectList(service.GetClientSet(), "ClientId", "Name", intervention.ClientId);
            ViewBag.Type = new SelectList(service.GetInterventionTypeSet(), "Id", "TypeName", intervention.Type);
            return View(intervention);
        }


        public ActionResult Cancel(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Intervention intervention = service.FindInterventionById(id);
            if (intervention == null)
            {
                return HttpNotFound();
            }
            return View(intervention);
        }

        [HttpPost, ActionName("Cancel")]
        public async Task<ActionResult> CancelConfirmed(int? id)
        {
            var emailFormService = new EmailHelpService();
            
            service.UpdateInterventionStateToCanceled(id);
            return await emailFormService.SendEmail("Cancel", id, "History");
        }

        public JsonResult GetDefaultCostAndLabor(int id)
        {
            // Build a object of label values based on the selected language ID
            var result = service.FindInterventionType(id);
            var data = new
            {
                Success = true,
                Cost = result.DefaultCost,
                Label = result.DefaultLabour
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

EnterpriseAssignment2/Views/Intervention/Cancel.cshtml
@model EnterpriseAssignment2.Models.Intervention

@{
    ViewBag.Title = "Cancel";
}

<h2>Cancel</h2>

<h3>Are you sure you want to cancel this?</h3>
<div>
    <h4>Intervention</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LabourRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LabourRequired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PerformedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PerformedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecentVisitDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecentVisitDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RemainingLife)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RemainingLife)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProposingUserObject.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProposingUserObject.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovalUserObject.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovalUserObject.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterventionType.TypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterventionType.TypeName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Cancel" class="btn btn-default" /> |
            @Html.ActionLink("Back to History List", "History")
        </div>
    }
</div>

EnterpriseAssignment2/Views/Intervention/Create.cshtml
@model EnterpriseAssignment2.Models.Intervention

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Intervention</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClientId, "ClientId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>
        
        @*<div class="form-group">
            @Html.LabelFor(model => model.ProposingUser.Where(p => p.ToString() == User.Identity.Name), "ProposingUser", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProposingUser", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProposingUser, "", new { @class = "text-danger" })
            </div>
        </div>*@
        @*@{ Model.ProposingUser = User.Identity.Name}*@

        <div class="form-group">
            @Html.LabelFor(model => model.LabourRequired, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.EditorFor(model => model.LabourRequired, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LabourRequired, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Client's Intervention List", "List_Client", new { id = Html.ViewContext.RouteData.Values["id"] })
</div>

<script type="text/javascript">
    var url = '@Url.Action("GetDefaultCostAndLabor", "Intervention")';
    $(document).ready(function () {
        $.getJSON(url + "/1", function (response) {
            $('#LabourRequired').val(response.Label);
            $('#Cost').val(response.Cost);
        })
    });
    $('#Type').change(function(){
        $.getJSON(url + "/" + $(this).val(), function (response) {
            $('#LabourRequired').val(response.Label);
            $('#Cost').val(response.Cost);
        })
    });
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnterpriseAssignment2/Views/Intervention/Details.cshtml
@model EnterpriseAssignment2.Models.Intervention

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Intervention</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LabourRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LabourRequired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PerformedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PerformedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecentVisitDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecentVisitDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RemainingLife)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RemainingLife)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProposingUserObject.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProposingUserObject.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApprovalUserObject.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApprovalUserObject.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Client.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Client.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InterventionType.TypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InterventionType.TypeName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to History List", "History", new { id = Model.Client.ClientId }) |
    @Html.ActionLink("Back to Same Client's Intervention List", "List_Client", new { id = Model.Client.ClientId })
</p>

EnterpriseAssignment2/Views/Intervention/Edit.cshtml
@model EnterpriseAssignment2.Models.Intervention

@{
    ViewBag.Title = "Change Quality Information";
}

<h2>Change Quality Information</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Intervention</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.InterventionId)

        <div class="form-group">
            @Html.LabelFor(model => model.Client.Name, "Client", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Client.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProposingUserObject.UserName, "Proposing User", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ProposingUserObject.UserName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApprovalUserObject.UserName, "Approval User", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ApprovalUserObject.UserName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InterventionType.TypeName, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.InterventionType.TypeName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LabourRequired, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.LabourRequired, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PerformedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.PerformedDate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecentVisitDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.RecentVisitDate, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RemainingLife, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RemainingLife, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RemainingLife, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>

    }

<div>
    @Html.ActionLink("Back to Client's Intervention List", "List_Client", new { id = Model.ClientId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EnterpriseAssignment2/Views/Intervention/History.cshtml
@model IEnumerable<EnterpriseAssignment2.Models.Intervention>

@{
    ViewBag.Title = "History";
}

<h2>Intervention history list</h2>

<p>
    @Html.ActionLink("Back to Client List", "../Client/Index")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LabourRequired)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PerformedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RecentVisitDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RemainingLife)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProposingUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApprovalUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Client.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InterventionType.TypeName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Where(i => !i.State.Contains("Completed")))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LabourRequired)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PerformedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecentVisitDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RemainingLife)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProposingUserObject.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApprovalUserObject.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InterventionType.TypeName)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.InterventionId }) |
                @Html.ActionLink("Cancel", "Cancel", new { id = item.InterventionId })
            </td>
        </tr>
    }

    @foreach (var item in Model.Where(i => i.State.Contains("Completed")))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LabourRequired)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PerformedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecentVisitDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RemainingLife)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProposingUserObject.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApprovalUserObject.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Client.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InterventionType.TypeName)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.InterventionId })
            </td>
        </tr>
    }
</table>